### ISSUE TITLE
Forth not available after on/off

### ISSUE THREAD

**Issue by L-andee** [Robert-van-Engelen/Forth500#1]
Hi,
first of all: This is a great project! Congratulations on your splendid work!

I do have a problem, though: I can load the binary image without problems via cassette interface and the WAVs you provided, and Forth500 starts up and exits fine. However, after I switch off and on again, I cannot re-call Forth (via CALL &B000) - the computer just shows BUSY and hangs; I can only recover it via a RESET.

I changed all batteries, including the lithium CR2016, but no luck.

Is there something I am doing wrong?

Thanks,
Andreas

**Comment by Robert-van-Engelen** [comment]
I haven't had such an issue on expanded and unexpanded E500. Turning ON/OFF has no effect. If you allocated memory in advance (see instructions), then you should be fine. If memory is not allocated then Forth500 will crash sooner or later.

However, if a faulty Forth program destroys the dictionary then you may see the system hang or misbehave. The best way is to save the Forth500 image to RAM disk, then run a program to test. If things fail, just reload the image from RAM disk. See the `SAVE` command in the additions/SAVE.FTH file.

**Comment by Robert-van-Engelen** [comment]
I should also add that pressing OFF/ON doesn't have much of an effect at all on the machine's state, because it simply turns the machine into a low power state that is restored with ON. It's just a system call that returns when the machine is turned back on.

Executing BYE to return to BASIC and then back to Forth500 with CALL&B0000 (or CALL&B9000 when applicable) will restart Forth500 with the dictionary unchanged. If it hangs, then Forth500 was damaged. That can happen when memory allocation failed before Forth500 was loaded into memory, thus the loaded Forth500 is not protected and can be damaged by the BASIC interpreter or by the system. Check that memory allocation for Forth500 was successful (see the README).

**Comment by L-andee** [comment]
Thank you very much for the hints! I managed to run the „unexpanded” version in the meantime. At this point I suspect my RAM card to be the culprit, I believe it might be faulty. 
I’ll let you know once I have confirmation. 

Thanks again,
Andreas

**Comment by Robert-van-Engelen** [comment]
I should add that a 32KB RAM card does not suffice to run the expanded version even with `MEM$="B"`. I will add a note about that in the README under E500-expanded. If there is some demand for this, then I could create a third version of Forth500 that runs with a 32KB RAM card with `MEM$="B"` specifically.
